#!/bin/sh

if [ -z "$MESA_TOOLING_ENV" ]; then
    if [ -z "$MESA_TOOLING_DEV_DIR" ]; then
        export MESA_TOOLING_DEV_DIR=$HOME/dev
    fi

    if [ -z "$MESA_TOOLING_BUILD_DIR" ]; then
        export MESA_TOOLING_BUILD_DIR=$HOME/build
    fi

    if [ -z "$DEQP_TOOLS_BUILD_DIR" ]; then
        export DEQP_TOOLS_BUILD_DIR=/deqp-tools
    fi

    if [ -z "$DEQP_VK_BUILD_DIR" ]; then
        export DEQP_VK_BUILD_DIR=/deqp-vk
    fi

    if [ -z "$DEQP_GL_BUILD_DIR" ]; then
        export DEQP_GL_BUILD_DIR=/deqp-gl
    fi

    if [ -z "$DEQP_GLES_BUILD_DIR" ]; then
        export DEQP_GLES_BUILD_DIR=/deqp-gles
    fi

    export MESA_BUILD_BASE_DIR=$MESA_TOOLING_BUILD_DIR/mesa
    export CL_CTS_BUILD_DIR=$MESA_TOOLING_BUILD_DIR/OpenCL-CTS
    export CL_ICD_BUILD_DIR=$MESA_TOOLING_BUILD_DIR/OpenCL-ICD-Loader

    export MESA_ROOT_DIR=$MESA_TOOLING_DEV_DIR/mesa
    export CL_CTS_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-CTS
    export CL_ICD_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-ICD-Loader
    export CL_HEADERS_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-Headers

    export MESA_TOOLING_ENV=1
fi


