#!/bin/sh

if [ -z "$MESA_TOOLING_ENV" ]; then
    if [ -z "$MESA_TOOLING_DEV_DIR" ]; then
        export MESA_TOOLING_DEV_DIR=$HOME/dev
    fi

    if [ -z "$MESA_TOOLING_BUILD_DIR" ]; then
        export MESA_TOOLING_BUILD_DIR=$HOME/build
    fi

    export MESA_BUILD_BASE_DIR=$MESA_TOOLING_BUILD_DIR/mesa
    export VK_GL_CTS_BUILD_DIR=$MESA_TOOLING_BUILD_DIR/VK-GL-CTS
    export CL_CTS_BUILD_DIR=$MESA_TOOLING_BUILD_DIR/OpenCL-CTS
    export CL_ICD_BUILD_DIR=$MESA_TOOLING_BUILD_DIR/OpenCL-ICD-Loader

    export MESA_ROOT_DIR=$MESA_TOOLING_DEV_DIR/mesa
    export VK_GL_CTS_ROOT_DIR=$MESA_TOOLING_DEV_DIR/VK-GL-CTS
    export CL_CTS_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-CTS
    export CL_ICD_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-ICD-Loader
    export CL_HEADERS_ROOT_DIR=$MESA_TOOLING_DEV_DIR/OpenCL-Headers

    export VULKAN_CTS_PATH=$VK_GL_CTS_ROOT_DIR/external/vulkancts
    export OPENGL_CTS_PATH=$VK_GL_CTS_ROOT_DIR/external/openglcts

    export MESA_TOOLING_ENV=1
fi


